### ISSUE TITLE
Will this plugin works for devtool extensions? 

### ISSUE THREAD

**Issue by Lil-C0der** [pacexy/mv3-hot-reload#2]
I am currently working on building a [chrome devtool extension](https://developer.chrome.com/docs/extensions/mv3/devtools/) with `cra` and `react-app-rewired`. But Webpack's HMR seems doesn't work. I am wondering if this plugin be able to reload a **devtool extension**

**Comment by pacexy** [comment]
This plugin is just for scripts. If you want to make your UI hot-reloadable, the following repositories may be able to help you.
- [pacexy/chrome-extension-typescript-starter](https://github.com/pacexy/chrome-extension-typescript-starter) (with `react-refresh`)
- [lxieyang/chrome-extension-boilerplate-react] (https://github.com/lxieyang/chrome-extension-boilerplate-react) (with `react-hot-loader`)
