### ISSUE TITLE
Getting upgrade error after setup

### ISSUE THREAD

**Issue by adventurini** [pacexy/mv3-hot-reload#3]
I have installed and gone through the steps, but I am getting this error. It still requires a full refresh of the extension.

I am using the latest version v0.2.5.

![Screen Shot 2021-08-30 at 9 37 44 AM](https://user-images.githubusercontent.com/12114942/131348040-4cec5750-6128-4b75-8395-9056470e25ec.png)

`package.json`

``` 
"scripts": {
    "build": "node utils/build.js",
    "start": "node utils/webserver.js",
    "watch:build": "mv3-hot-reload",
    "dev": "concurrently yarn:watch:*",
    "prettier": "prettier --write '**/*.{js,jsx,css,html}'"
  },
```

`mv3-hot-reload.config.js`

```
module.exports = {
    port: 9012,
    directory: 'build',
    exclude: [],
  }
```
`content.ts`

```
import React from 'react';

const Content = () => {
  return (
    <div
      className="ContentContainer"

    >
      Test
    </div>
  );
};

export default Content;
```

File directory structure:
![Screen Shot 2021-08-30 at 9 28 28 AM](https://user-images.githubusercontent.com/12114942/131346583-84cc0a49-a72c-4c24-901c-6e1dfbeedebb.png)

**Comment by pacexy** [comment]
Please refer to https://github.com/pacexy/chrome-extension-typescript-starter to set up correctly. If the problem still exists, please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction/).
