### ISSUE TITLE
webpack injection imrovement

### ISSUE THREAD

**Issue by s-KaiNet** [pacexy/mv3-hot-reload#5]
It's not an issue, but just a hint on how you can further slightly improve the way of injecting the reload code. 
You can leverage weback's ["multi-main entry"](https://webpack.js.org/concepts/entry-points/). Taking your [config here](https://github.com/pacexy/chrome-extension-typescript-starter/blob/master/webpack.config.ts):

```js
entry: {
    popup: path.join(srcDir, 'popup'),
    options: path.join(srcDir, 'options'),
    background: isDev ? ['mv3-hot-reload/background', path.join(srcDir, 'background')] : path.join(srcDir, 'background'),
    content: isDev? ['mv3-hot-reload/content', path.join(srcDir, 'content')] : path.join(srcDir, 'content'),
  },
```
In this case, the reload code will only be injected into the dev build and will not be even available in production. Also, you don't need to add `import 'mv3-hot-reload/background'` etc. into your scripts.

**Comment by pacexy** [comment]
Looks great! Thanks for your suggestion.
