### ISSUE TITLE
Can you please give several explanations?

### ISSUE THREAD

**Issue by lofti198** [pacexy/mv3-hot-reload#7]
Hi! Thank you for this solution! It is really awesome. Can you please explain several things:
1. what is the purpose in this case to use Webpack's "multi-main entry" ?
2. before running development, should I start all of watch:src, watch:dist and dev commands? If so , can I combine them as one command?
3. which files typically should be excluded in watched directory?
4. if I do not use typescript is that almost all the same, except of I ignore types in method definitions like here: `function getEntry(name: string) ` ?

**Comment by pacexy** [comment]
1. With "multi-main entry", you don't need to place the import code in scripts, which means it's decoupled for scripts.
2. Actually, `"dev": "concurrently yarn:watch:*"` script will run all the `watch:*` script concurrently.
3. If you don't know which files should be excluded, you don't need to specify it.
4. Yes, just remove the types.
